### ISSUE TITLE
Cannot read property 'callbackService' of undefined

### ISSUE THREAD

**Issue by Vanyla-Vvv** [negezor/vk-io#343] opened 2020-09-24 16:59 UTC
F:\nodejs\node_modules\vk-io\lib\index.js:8593
        this.callbackService = options.callbackService
                                       ^

TypeError: Cannot read property 'callbackService' of undefined
    at new VK (F:\nodejs\node_modules\vk-io\lib\index.js:8593:40)
    at Object.<anonymous> (F:\nodejs\vkfr.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by trackerfloat** [comment] 2020-09-25 00:05
Duplicate of #317

**Closed** 2020-09-25 06:21 UTC
